<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-07 at 16:43:00.
 */
class AutoloadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testCObject()
    {
        $obj = new \Fac\CObject();
        $this->assertInstanceOf('\Fac\CObject', $obj);
    }

    public function testCDataObject()
    {
        $obj = new \Fac\CDataObject();
        $this->assertInstanceOf('\Fac\CDataObject', $obj);
    }

    public function testCListObject()
    {
        $obj = new \Fac\CListObject();
        $this->assertInstanceOf('\Fac\CListObject', $obj);
    }

    public function testCArrayObject()
    {
        $obj = new \Fac\CArrayObject();
        $this->assertInstanceOf('\Fac\CArrayObject', $obj);
    }

    public function testCSession()
    {
        $obj = new \Fac\CSession();
        $this->assertInstanceOf('\Fac\CSession', $obj);
    }

    public function testCObjectCollection()
    {
        $obj = new \Fac\CObjectCollection();
        $this->assertInstanceOf('\Fac\CObjectCollection', $obj);
    }
}