<?php

namespace Fac;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-07 at 18:06:26.
 */
class CSessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var CSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CSession;
        $this->object->id('testcliid');
        //Reset session
        $_SESSION = array();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        //Reset session
        //$_SESSION = array();
    }


    public function testLoad()
    {
        $this->assertInstanceOf('\Fac\CSession', $this->object);
    }

}